# Generated by Django 3.1.1 on 2020-11-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201109_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
